databases:
  - name: grant_sass_db
    databaseName: grant_sass_production
    user: grant_sass_user
    plan: free

services:
  - type: web
    name: grant_sass
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grant_sass_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: RAILS_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: APP_HOST
        sync: false
      - key: MAILER_FROM_EMAIL
        value: "no-reply@example.com"
